// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj5zxhL5qQu-Fj5gVWQGLR4q6R5JLfoZU',
    appId: '1:356183221644:android:13ca4e6344337e56a722a9',
    messagingSenderId: '356183221644',
    projectId: 'lets-chats-cb93b',
    storageBucket: 'lets-chats-cb93b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl1yjtOcfEQaRsTiRmojYGafJveEkMP70',
    appId: '1:356183221644:ios:d23088d847f01bfaa722a9',
    messagingSenderId: '356183221644',
    projectId: 'lets-chats-cb93b',
    storageBucket: 'lets-chats-cb93b.appspot.com',
    androidClientId: '356183221644-8tsgr2dlcrgdvrl1b0b4nqjout3floqk.apps.googleusercontent.com',
    iosClientId: '356183221644-am6b898cknjmkug6se1jp1msfsbah3n4.apps.googleusercontent.com',
    iosBundleId: 'com.example.myChatApp',
  );
}
